server:
  port: ${PORT:8080}
  servlet:
      context-path: /createjavafile
spring:
 application:
     name: crud-model-from-oracle #指定实例id
 datasource:
     druid:
           url: jdbc:oracle:thin:@10.9.47.106:1521:mmsdbuat
           username: SCDA
           password: SCDA1234
           driverClassName: oracle.jdbc.OracleDriver
           initialSize: 5  #初始建立连接数量
           minIdle: 5  #最小连接数量
           maxActive: 20 #最大连接数量
           maxWait: 10000  #获取连接最大等待时间，毫秒
           testOnBorrow: true #申请连接时检测连接是否有效
           testOnReturn: false #归还连接时检测连接是否有效
           timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
           minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
     type: com.alibaba.druid.pool.DruidDataSource
 freemarker:
       cache: false  #关闭模板缓存，方便测试
       settings:
         template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
mybatis:
 type-aliases-package: com.pccw.createjavafile.domain
 mapper-locations: classpath:com/pccw/createjavafile/mapper/*Mapper.xml




