server:
  port: ${PORT:40200}
spring:
 application:
     name: scda-service-purchasecontrol #指定实例id
 datasource:
     druid:
           url: jdbc:oracle:thin:@10.9.47.106:1521:mmsdbuat
           username: SCDA
           password: SCDA1234
           driverClassName: oracle.jdbc.OracleDriver
           initialSize: 5  #初始建立连接数量
           minIdle: 5  #最小连接数量
           maxActive: 20 #最大连接数量
           maxWait: 10000  #获取连接最大等待时间，毫秒
           testOnBorrow: true #申请连接时检测连接是否有效
           testOnReturn: false #归还连接时检测连接是否有效
           timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
           minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
     type: com.alibaba.druid.pool.DruidDataSource

mybatis:
 type-aliases-package: com.pccw.framework.domain.purchaseexecute
 mapper-locations: classpath:com/pccw/task/mapper/*Mapper.xml



