server:
  port: ${PORT:40100}
  servlet:
      context-path: /createtable
spring:
 application:
     name: create-table-from-excel #指定实例id
 datasource:
     druid:
           url: jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9.70.162  )(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9.70.164 )(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = mmsdb)(failover_mode =(type = session))))
           username: scda
           password: Scda2019#
           driverClassName: oracle.jdbc.OracleDriver
           initialSize: 5  #初始建立连接数量
           minIdle: 5  #最小连接数量
           maxActive: 20 #最大连接数量
           maxWait: 10000  #获取连接最大等待时间，毫秒
           testOnBorrow: true #申请连接时检测连接是否有效
           testOnReturn: false #归还连接时检测连接是否有效
           timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
           minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
     type: com.alibaba.druid.pool.DruidDataSource

mybatis:
 type-aliases-package: com.xcl.createtable.domain
 mapper-locations: classpath:com/xcl/createtable/dao/*Dao.xml




